name: CI
on: [ push, pull_request ]
jobs:
  Build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 16 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run all
    - name: Update Example
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      env:
        GIT_USER_NAME: ${{secrets.BPMN_IO_USERNAME}}
        GIT_USER_EMAIL: ${{secrets.BPMN_IO_EMAIL}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: tasks/update-example